name: github to gitee

on:
  push:
    branches:
      - main

jobs:
  docs-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: sync-gitee-mirror
        uses: abersheeran/sync-gitee-mirror@v1-beta
        with:
          repository: yzqdev/yzqdev
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
